# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
#include:
#- template: Security/Secret-Detection.gitlab-ci.yml

stages:
#  - test
  - beta
  - build
  - upload
  - beta_release
  - release


variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  CI_COMMIT_TAG: "2.0.0.b8"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/networksharemounter/${CI_COMMIT_TAG}"
  PACKAGE: "NetworkShareMounter.dmg"

before_script:
  - cp /Users/autopkg/dev/networkShareMounter/.env.default .
#  - gem install bundler
#  - pod install

#test_build:
#  stage: test
#  script:
#    - echo "One day some tests will be done and there will be light"
#  tags:
#    - fastlane
#    - xcode

beta build:
  dependencies: []
  stage: beta
  rules:
    - if: '$CI_COMMIT_TAG =~ /^beta-/'
  script:
    - fastlane beta
  artifacts:
    paths:
      - swiftlint.result.json
      - build/NetworkShareMounterBeta.dmg
    expire_in: 1 hour
  tags:
    - fastlane
    - xcode

deploy build:
  dependencies: []
  stage: build
  rules:
  - if: '$CI_COMMIT_TAG =~ /^release-/'
  script:
    - fastlane release
  artifacts:
    paths:
     - swiftlint.result.json
      - build/NetworkShareMounter.dmg
    expire_in: 1 hour
  tags:
    - fastlane
    - xcode

upload:
  stage: upload
  rules:
  - if: '$CI_COMMIT_TAG =~ /^release-/'
  script:
    - '/usr/bin/curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${PACKAGE} ${PACKAGE_REGISTRY_URL}/${PACKAGE}'
  dependencies:
    - beta build
    - deploy build
  tags:
    - fastlane
    - xcode

beta release:
  variables:
    PACKAGE: "NetworkShareMounterBeta.dmg"
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^beta-/'
  script:
    - '/usr/local/bin/release-cli create --name "Beta $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG --assets-link "{\"name\":\"${PACKAGE}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE}\"}"'
  dependencies:
    - beta build
    - upload
  tags:
    - fastlane
    - xcode

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^release-/'
  script:
    - '/usr/local/bin/release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG --assets-link "{\"name\":\"${PACKAGE}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE}\"}"'
  dependencies:
    - deploy build
    - upload
  tags:
    - fastlane
    - xcode

  
