# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
#include:
#- template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - test
  - beta
  - release
#  - test
#  - archive
#  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - cp /Users/autopkg/dev/networkShareMounter/.env.default .
#  - gem install bundler
#  - pod install

test:
  stage: test
  script:
      - echo "Test have to e tested to test something someday"
  tags:
    - fastlane
    - xcode

beta_build:
  dependencies: []
  stage: beta
  script: 
    - fastlane beta
  artifacts:
    paths:
      - build/NetworkShareMounterBeta.dmg
      - swiftlint.result.json
      expire_in: 1 hour

  tags:
    - fastlane
    - xcode

deploy_build:
  dependencies: []
  stage: release
  script:
    - echo "running fastlane"
    - fastlane releae
  artifacts:
    paths:
      #- swiftlint.result.json
      expire_in: 1 day
  tags:
    - fastlane
    - xcode
    only:
      - /^release-.*$/
      - master

