# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
#include:
#- template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - test
  - build
  - upload
  - release


variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/networksharemounter/${CI_COMMIT_TAG}"
  DMG: "NetworkShareMounter.dmg"
  PACKAGE: "NetworkShareMounter.pkg"

before_script:
  - cp /Users/autopkg/dev/networkShareMounter/.env.default .
  - export APP_VERSION=`echo "$CI_COMMIT_TAG" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+'`
#  - gem install bundler
#  - pod install

test_build:
  stage: test
  variables:
    DMG: 'NetworkShareMounterBeta-"$APP_VERSION".dmg'
    PACKAGE: "NetworkShareMounterBeta-${APP_VERSION}.pkg"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^test-/'
  script:
    #- fastlane test
    - 'echo Variable APP_VERSION is: ${APP_VERSION}'
    - 'echo Variable APP_VERSION is: "$APP_VERSION"'
    - 'echo Variable DMG is: "$DMG"'
    - 'echo Variable DMG is: ${PKG}'
    - 'echo will do: "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${DMG} ${PACKAGE_REGISTRY_URL}/${DMG}'
    - 'echo will do: "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${PKG} ${PACKAGE_REGISTRY_URL}/"$PKG"'
  artifacts:
    paths:
      - swiftlint.result.json
      - build/*dmg
      - build/*pkg
    expire_in: 1 hour
  tags:
    - fastlane
    - xcode

beta build:
  stage: build
  variables:
    DMG: "NetworkShareMounterBeta-${APP_VERSION}.dmg"
    PACKAGE: "NetworkShareMounterBeta-${APP_VERSION}.pkg"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^beta-/'
  script:
    - fastlane beta
  artifacts:
    paths:
      - swiftlint.result.json
      - build/*dmg
      - build/*pkg
    expire_in: 1 hour
  tags:
    - fastlane
    - xcode

release build:
  stage: build
  rules:
  - if: '$CI_COMMIT_TAG =~ /^release-/'
  script:
    - fastlane release
  artifacts:
    paths:
      - swiftlint.result.json
      - build/*dmg
      - build/*pkg
    expire_in: 1 hour
  tags:
    - fastlane
    - xcode

beta upload:
  stage: upload
  variables:
    DMG: "NetworkShareMounterBeta.dmg"
    PACKAGE: "NetworkShareMounterBeta.pkg"
  rules:
  - if: '$CI_COMMIT_TAG =~ /^beta-/'
  script:
    - '/usr/bin/curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${DMG} ${PACKAGE_REGISTRY_URL}/${DMG}'
    - '/usr/bin/curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${PACKAGE} ${PACKAGE_REGISTRY_URL}/${PACKAGE}'
  dependencies:
    - beta build
  tags:
    - fastlane
    - xcode

release upload:
  stage: upload
  rules:
  - if: '$CI_COMMIT_TAG =~ /^release-/'
  script:
    - '/usr/bin/curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${DMG} ${PACKAGE_REGISTRY_URL}/${DMG}'
    - '/usr/bin/curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file build/${PACKAGE} ${PACKAGE_REGISTRY_URL}/${PACKAGE}'
  dependencies:
    - release build
  tags:
    - fastlane
    - xcode

beta release:
  variables:
    DMG: "NetworkShareMounterBeta.dmg"
    PACKAGE: "NetworkShareMounterBeta.pkg"
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^beta-/'
  script:
    - '/usr/local/bin/release-cli create --name "$CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG --assets-link "{\"name\":\"${PACKAGE}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE}\"}" --assets-link "{\"name\":\"${DMG}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${DMG}\"}"'
  dependencies:
    - beta build
    - beta upload
  tags:
    - fastlane
    - xcode

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^release-/'
  script:
    - '/usr/local/bin/release-cli create --name "$CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG --assets-link "{\"name\":\"${PACKAGE}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${PACKAGE}\"}" --assets-link "{\"name\":\"${DMG}\",\"url\":\"${PACKAGE_REGISTRY_URL}/${DMG}\"}"'
  dependencies:
    - release build
    - release upload
  tags:
    - fastlane
    - xcode
