#!/bin/zsh
############################################
## Network Share Mounter- Postinstall script
############################################
currentUser=$(/usr/bin/stat -f%Su /dev/console)
IFS=$'\n' nsm_pids=($(pgrep Network Share Mounter))

# Restart Network Share Mounter if currently running
if [[ ! -z $nsm_pids ]]; then
    for nsm_pid in ${nsm_pids[*]}; do
        echo "PID $nsm_pid found"
        kill -s QUIT "$nsm_pid"
        echo "Restart Network Share Mounter"
        sudo -u $currentUser open -a /Applications/Network\ Share\ Mounter.app
    done
else
	echo "Network Share Mounter not running"
fi
