# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Description of what the lane does"
  lane :custom_lane do
    notarize(
        package: app_path, # Path to package to notarize, e.g. .app bundle or disk image
        bundle_id: bundle_id # Not required for .app bundles, bundle identifier to uniquely identify the package.
    )
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :test do
  teams_bot(
    teams_url: 'https://msfau.webhook.office.com/webhookb2/c4d73242-1890-4708-a7e9-98cf6e590eb9@b2efcef3-8496-40b8-9de8-f135982f3461/IncomingWebhook/6c157802c97c49d183cc9e01702025ff/b6ea7d2d-0dbc-4cdf-b543-9af44c258ea7',
    title: 'Welcome from Fastlane',
    summary: 'Integration is a success',
    text: 'Hi there !! I am [Teams Bot](https://github.com/huextrat/fastlane-plugin-teams_bot). I can send messages on Microsoft Teams very easily from Fastlane.',
    activity_title: 'Hey',
    activity_subtitle: 'Working on Fastlane',
    activity_image: 'https://seeklogo.com/images/F/fastlane-logo-6CA0B0B428-seeklogo.com.png',
    facts: [
      {
        'name' => 'Environment',
        'value' => 'Staging'
      },
      {
        'name' => 'Branch',
        'value' => 'Develop'
      }
    ],
    theme_color: '321244',
    use_markdown: true
  )
end
